import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    imageContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        width: '105%',
        height: '100%',
        position: 'relative',
    },
    image: {
        zIndex: 1,
    },
    text: {
        width: '25%',
        textAlign: 'left',
        position: 'absolute',
        fontSize: 5,
        top: '38.7%',
        left: '3.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text2: {
        width: '19%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 5,
        top: '39.97%',
        left: '10%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text3: {
        width: '15%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 7,
        paddingTop: 1,
        top: '46.25%',
        left: '26%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text4: {
        width: '16.2%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 7,
        top: '49%',
        left: '15%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text5: {
        width: '16.2%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 7,
        paddingTop: 2,
        top: '56.07%',
        left: '15%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text6: {
        width: '8%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 5,
        top: '60.25%',
        left: '29%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text7: {
        width: '8%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 5,
        top: '61.55%',
        left: '5.2%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    text8: {
        width: '16.2%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 7,
        paddingTop: 2,
        top: '67%',
        left: '4.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext: {
        width: '11%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 4,
        top: '36.46%',
        right: '20%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext2: {
        width: '7%',
        textAlign: 'left',
        position: 'absolute',
        fontSize: 4,
        top: '37.3%',
        right: '19.2%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext3: {
        width: '11%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 4,
        top: '38.05%',
        right: '20%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext4: {
        width: '20%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '42.53%',
        right: '20%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext5: {
        width: '25%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '43.83%',
        right: '14%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext6: {
        width: '12%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '45%',
        right: '17%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext7: {
        width: '10%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '45%',
        right: '2.59%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext8: {
        width: '35%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '46.2%',
        right: '3.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext9: {
        width: '13%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '47.72%',
        right: '20.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext10: {
        width: '9%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '47.72%',
        right: '3.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext11: {
        width: '14%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '49%',
        right: '20.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext12: {
        width: '10%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 6,
        top: '49%',
        right: '3.5%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
    secondtext13: {
        width: '17%',
        textAlign: 'center',
        position: 'absolute',
        fontSize: 8,
        top: '63.8%',
        right: '8%',
        zIndex: 0,
        color: 'black',
        backgroundColor: 'white',
    },
});

export default styles;
