import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    containerTitle: {
        marginTop: 30,
    },
    title: {
        fontSize: 10,
        textAlign: "center",
    },
    titleMain: {
        fontSize: 12,
        textAlign: "center",
        marginTop: 17,
        marginBottom: 15,
        fontWeight: "bold",
        textDecoration: "underline",
    },
    titleMainSecond: {
        fontSize: 12,
        textAlign: "center",
        marginBottom: 20,
        fontWeight: "bold",
    },
    containerForm:{
        flexDirection: "column",
        width: "100%",
        marginBottom: 10,
        paddingHorizontal: 30,
    },
    containerSecondForm:{
        flexDirection: "row",
        width: "100%",
        marginBottom: 15,
    },
    containerFormDone:{
        flexDirection: "column",
        width: "70%",
        marginBottom: 15,
        paddingHorizontal: 30,
    },
    containerFormDone2:{
        flexDirection: "column",
        width: "80%",
        marginBottom: 15,
        textAlign: "center",
        alignSelf: "center",
    },
    containerDate:{
        flexDirection: "column",
        width: "100%",
        textAlign: "center",
        alignContent: "center",
        alignItems: "flex-end",
    },
    containerFinal:{
        flexDirection: "column",
        width: "100%",
        textAlign: "center",
        alignContent: "center",
        alignItems: "center",
        marginBottom: 15,
    },
    label: {
        fontSize: 10,
        textAlign: "left",
    },
    labelDate: {
        width: "52%",
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
    },
    underlineData: {
        width: 0,
        color: '#FF0000',
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
        borderBottomWidth: 1,
        paddingLeft: 5,
    },
    underlineDataSecond: {
        width: "55%",
        color: '#FF0000',
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
        borderBottomWidth: 1,
        paddingLeft: 5,
    },
    underlineDataSecond2: {
        width: "30%",
        color: '#FF0000',
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
        borderBottomWidth: 1,
        paddingLeft: 5,
    },
    underlineDate: {
        width: "30%",
        color: '#FF0000',
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
        borderBottomWidth: 1,
        marginRight: 55,
    },
    underline: {
        width: "32%",
        fontWeight: 'bold',
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
        borderBottomWidth: 1,
        marginRight: 50,
    },
    underlineFinal: {
        width: "30%",
        color: '#FF0000',
        textAlign: 'center',
        flexGrow: 1,
        fontSize: 10,
        borderBottomWidth: 1,
    },
    column:{
        flexDirection: "column",
        width: "100%",
    },
    columnSecond:{
        flexDirection: "column",
        width: "100%",
        textAlign: "center",
        alignContent: "center",
        alignItems: "center",
    },
    columnSecond2:{
        flexDirection: "column",
        width: "100%",
        textAlign: "center",
        alignContent: "center",
        alignItems: "center",
        marginHorizontal: 30,
    },
    row:{
        flexDirection: "row",
        width: "100%",
    },
});

export default styles;
